CREATE DATABASE abc_orders;


USE abc_orders;

SELECT *
FROM orders
LIMIT 10;

DESCRIBE orders;
DESCRIBE products;
DESCRIBE account_managers;

SET SQL_SAFE_UPDATES=0;

UPDATE orders
SET order_date=STR_TO_DATE(order_date,'%m/%d/%Y'),
	ship_date=STR_TO_DATE(ship_date,'%m/%d/%Y');
    
ALTER TABLE orders
MODIFY COLUMN order_date date,
MODIFY COLUMN ship_date date;

SELECT COUNT(*)
FROM orders
WHERE order_no IS NULL;

-- Checking for duplicates 
SELECT order_no, COUNT(order_no)
FROM orders
GROUP BY order_no
HAVING COUNT(order_no)>1;

SELECT *
FROM orders
WHERE order_no='5768-2' OR order_no='6159-2';

SET SQL_SAFE_UPDATES=1;

-- 1 WHAT IS THE TOTAL REVENUE GENERATED BY EACH PRODUCT CATEGORY?
SELECT product_category,
	ROUND(SUM(total),2) AS Reveneue
FROM orders
JOIN products
ON orders.product_id=products.product_id
GROUP BY product_category;
-- ANSWER: Office supplies: 343518.02, Technology: 831273.73, Furniture: 31920.3

-- 2 HOW MANY UNIQUE PRODUCTS HAVE BEEN ORDERED?
SELECT DISTINCT(COUNT(product_name)) AS Unique_Products
FROM products;
-- ANSWER: 147

-- 3 WHAT IS THE TOTAL REVENUE GENERATED EACH YEAR?
SELECT EXTRACT(YEAR from order_date)Year,
	ROUND(SUM(total),2)Revenue
FROM orders
GROUP BY YEAR;
-- ANSWER 2013=185547.2, 2014=339841.08, 2015=383167.13, 2016=273561.12, 2017=23595.52

-- 4 WHAT IS THE DATE OF THE LATEST AND EARLIEST ORDER?
SELECT MIN(order_date)'Earliest Date',
		MAX(order_date) Latest_date
FROM orders;
-- ANSWER earliest 2013-02-11 and latest 2017-02-07

-- 5 What product category has the lowest average price of products?
Select product_category,
		ROUND(AVG(retail_price),2)Average_price
FROM orders
JOIN products
USING(product_id)
GROUP BY product_category
ORDER BY Average_price
LIMIT 1;
-- ANSWER: OFFICE SUPPLIES 17.9

-- 6 What are the top 10 highest performing products?
SELECT product_name,
		ROUND(SUM(total),2)Revenue
FROM orders
JOIN products
Using(product_id)
Group BY product_name
Order BY Revenue DESC
LIMIT 10;
-- answer: graph top_10_products (saved on laptop)

-- 7 Show the total revenue and profit generated by each account_manager?
Select account_manager,
		ROUND(SUM(total),2)Revenue,
        ROUND(SUM(total) - SUM(cost_price),2) Profit
FROM orders
Join account_managers
USING (account_id)
GROUP BY account_manager
ORDER BY Revenue DESC;

-- 8 What is the name, city, and account manager of the highest selling product in 2017?
SELECT product_name,
		city,
        account_manager,
        ROUND(SUM(TOTAL))Revenue
FROM orders
JOIN products
Using (product_id)
JOIN account_managers
Using(account_id)
WHERE EXTRACT(year from order_date) = 2017
GROUP BY product_name,city, account_manager
ORDER BY Revenue DESC
LIMIT 1; 
-- ANSWER= UGEN ULTRA PROFESSIONAL CORDLESS OPTICAL SUITE, MELBOURE, 8735

-- 9 FIND THE MEAN AMOUNT SPENT PER ORDER BY EACH CUSTOMER TYPE
SELECT customer_type,
		AVG(total)Average_amount
From orders
Group BY customer_type;
-- Ansswer: Home office 1095.16, Corporate 1096.40, Consumer 1142.51, Small Business 1362.09

-- 10 What is the 5th highest selling product? 

SELECT product_name,
	ROUND(SUM(TOTAL),2)Revenue
FROM orders 
Join products 
USING (product_id)
GROUP BY product_name
ORDER BY revenue DESC 
LIMIT 5;

-- answer : UGEN ULTRA PRO CORDLESS OPTICAL SUITES, 68699.41